#!/bin/bash

# This script helps set up environment variables for deployment
# Run after completing each service signup

echo "=== Deployment Setup Assistant ==="
echo ""
echo "Complete these steps:"
echo ""
echo "1. NETLIFY SETUP"
echo "   - Go to https://netlify.com/auth/login"
echo "   - Sign in with GitHub"
echo "   - Go to User settings → Applications → Tokens"
echo "   - Generate new personal access token"
echo "   - Copy and save it"
echo ""
echo "2. NEON DATABASE SETUP"
echo "   - Go to https://neon.tech"
echo "   - Sign up with GitHub"
echo "   - Create new project"
echo "   - Copy connection string"
echo ""
echo "3. RENDER SETUP"
echo "   - Go to https://render.com"
echo "   - Sign up with GitHub"
echo "   - Create new Web Service from GitHub repo"
echo "   - Navigate to Deploy hook and copy URL"
echo ""
echo "4. GITHUB SECRETS"
echo "   - Go to GitHub repo → Settings → Secrets"
echo "   - Add:"
echo "     - NETLIFY_AUTH_TOKEN"
echo "     - NETLIFY_SITE_ID"
echo "     - RENDER_DEPLOY_HOOK"
echo ""
echo "Run './setup-env.sh' to generate environment files"
